"""empty message

Revision ID: 1cc99debf476
Revises: 13105331d208
Create Date: 2024-02-15 22:01:44.597893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cc99debf476'
down_revision = '13105331d208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint('session_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mentor', ['mentor_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('session_ibfk_1', 'user', ['mentor_id'], ['id'])

    # ### end Alembic commands ###
