"""empty message

Revision ID: 691d19476cc8
Revises: ec0cc5c46ca3
Create Date: 2024-02-07 13:28:41.880663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691d19476cc8'
down_revision = 'ec0cc5c46ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.String(length=200), nullable=True),
    sa.Column('availability', sa.String(length=200), nullable=True),
    sa.Column('languages_spoken', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mentor')

    op.drop_table('mentor')
    # ### end Alembic commands ###
