"""empty message

Revision ID: 830837a7cd50
Revises: 1d1f7453e03b
Create Date: 2024-02-15 22:40:42.877364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830837a7cd50'
down_revision = '1d1f7453e03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('meeting_url', sa.String(length=255), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
